"""
tests/test_hex_map.py — hex_map movement cost and ZOC rule verification.

Fixtures generated by the oracle agent from cna_rules.txt only (never src/).
Rules covered:
  8.37  Terrain Effects Chart — movement CP costs
  8.31  Road cost: ½ CP fixed for motorized units
  8.42  Up-escarpment prohibition for vehicles; 8 CP for foot
  8.46  Track cost: 1 CP per hex
  10.11 ZOC projection based on Stacking Points
  10.21 ZOC blocked by Major River and Escarpment hexsides; restricted
        by 10.21c (can't ZOC into hex you cannot enter)

Design: "see_tec" expected values → pytest.skip (OCR could not read TEC cell).
        "ambiguity" in expected → pytest.xfail (rule text unclear; may differ).
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

from conftest import load_fixture, case_id
from src.engine.hex_map import HexMap, _ZOC_BLOCKED_HEXSIDES, _ZOC_NEVER_TYPES
from src.models.hex import Hex, HexsideFeature, Terrain
from src.models.unit import Nationality, Side, Unit, UnitSize, UnitStatus, UnitType


# ── TEC fixture (loaded once per session) ─────────────────────────────────────

@pytest.fixture(scope="module")
def tec():
    path = Path(__file__).parent.parent / "data" / "extracted" / "rules_tables.json"
    with path.open() as f:
        d = json.load(f)
    return d.get("terrain_effects_chart", d)


# ── Mapping: fixture name strings → enums ─────────────────────────────────────

_FIXTURE_TERRAIN: dict[str, Terrain] = {
    "Desert":     Terrain.DESERT,
    "Rough":      Terrain.ROUGH,
    "Salt_Marsh": Terrain.SALT_MARSH,
    "Swamp":      Terrain.SWAMP,
    "Clear":      Terrain.CLEAR,
    "Oasis":      Terrain.VILLAGE,
}

_FIXTURE_HEXSIDE: dict[str, HexsideFeature] = {
    "None":            HexsideFeature.NONE,
    "Road":            HexsideFeature.ROAD,
    "Track":           HexsideFeature.TRACK,
    "Wadi":            HexsideFeature.WADI,
    "Ridge":           HexsideFeature.RIDGE,
    "Slope_Up":        HexsideFeature.SLOPE_UP,
    "Slope_Down":      HexsideFeature.SLOPE_DOWN,
    "Escarpment_Up":   HexsideFeature.ESCARPMENT_UP,
    "Escarpment_Down": HexsideFeature.ESCARPMENT_DOWN,
    "Major_River":     HexsideFeature.MAJOR_RIVER,
    "Minor_River":     HexsideFeature.MINOR_RIVER,
}

_FIXTURE_UNIT_TYPE: dict[str, UnitType] = {
    "infantry": UnitType.INFANTRY,
    "armor":    UnitType.ARMOR,
    "truck":    UnitType.TRUCK,
    "supply":   UnitType.SUPPLY,
    "hq":       UnitType.HQ,
}

_FIXTURE_UNIT_SIZE: dict[str, UnitSize] = {
    "company":   UnitSize.COMPANY,
    "battalion": UnitSize.BATTALION,
    "regiment":  UnitSize.REGIMENT,
    "brigade":   UnitSize.BRIGADE,
    "division":  UnitSize.DIVISION,
    "corps":     UnitSize.CORPS,
    "army":      UnitSize.ARMY,
}


# ── Hex pair for entry_cost tests ─────────────────────────────────────────────
# from_hex A0101 (section=A, col=1 odd), to_hex A0102 (south neighbor).
# Odd-column S-direction delta = (0, +1): row 1 → row 2 = A0102. ✓

_FROM = "A0101"
_TO   = "A0102"
_DIR  = "S"   # forward direction from _FROM → _TO


def _make_pair(to_terrain: Terrain, hexside: HexsideFeature) -> dict:
    """Construct a minimal {hex_id → Hex} dict for one entry_cost call."""
    from_hex = Hex.from_id(_FROM)
    from_hex.terrain = Terrain.DESERT   # source terrain doesn't affect entry cost

    to_hex = Hex.from_id(_TO)
    to_hex.terrain = to_terrain

    if hexside != HexsideFeature.NONE:
        from_hex.hexsides[_DIR] = hexside   # hexside on the forward side

    return {_FROM: from_hex, _TO: to_hex}


def _unit(motorized: bool) -> Unit:
    return Unit(
        id="test",
        name="Test",
        nationality=Nationality.BRITISH,
        side=Side.COMMONWEALTH,
        type=UnitType.INFANTRY,
        size=UnitSize.BATTALION,
        motorized=motorized,
    )


# ── 8.37 entry_cost parametrized tests ────────────────────────────────────────

_MOVEMENT_CASES = load_fixture("movement_costs_8_37")


@pytest.mark.parametrize(
    "case", _MOVEMENT_CASES,
    ids=[case_id(c) for c in _MOVEMENT_CASES],
)
def test_movement_cost(case, tec):
    inp = case["inputs"]
    exp = case["expected"]
    expected_cost = exp["cp_cost"]

    # Oracle could not read the TEC cell from OCR → need physical rulebook
    if expected_cost == "see_tec":
        pytest.skip("TEC cell not recoverable from OCR — physical rulebook required")

    # Oracle flagged a rule ambiguity — expected may differ from implementation
    if "ambiguity" in exp:
        pytest.xfail(reason=f"rule ambiguity: {exp['ambiguity'][:100]}")

    terrain_name = inp["to_terrain"]
    hexside_name = inp["hexside_feature"]
    motorized    = inp["motorized"]
    weather      = inp.get("weather", "clear")

    terrain = _FIXTURE_TERRAIN.get(terrain_name)
    if terrain is None:
        pytest.skip(f"terrain {terrain_name!r} not in test map")

    hexside = _FIXTURE_HEXSIDE.get(hexside_name)
    if hexside is None:
        pytest.skip(f"hexside {hexside_name!r} not in test map")

    hexes = _make_pair(terrain, hexside)
    hmap  = HexMap(hexes, tec)
    unit  = _unit(motorized)

    result = hmap.entry_cost(unit, _FROM, _TO, weather=weather)

    if expected_cost == "P":
        assert result == "P", (
            f"Expected prohibited (P) for terrain={terrain_name}, "
            f"hexside={hexside_name}, motorized={motorized}; got {result!r}"
        )
    else:
        assert isinstance(result, float), (
            f"Expected float cost, got {result!r}"
        )
        assert result == pytest.approx(expected_cost), (
            f"entry_cost mismatch: terrain={terrain_name}, hexside={hexside_name}, "
            f"motorized={motorized} → got {result}, expected {expected_cost}"
        )


# ── 10.11 stacking points spot checks ─────────────────────────────────────────

def test_division_stacking_points():
    """Division = 5 SP (rules_tables.json 9.4 stacking_rules)."""
    u = Unit(
        id="div", name="Division",
        nationality=Nationality.BRITISH, side=Side.COMMONWEALTH,
        type=UnitType.INFANTRY, size=UnitSize.DIVISION,
    )
    assert HexMap.unit_stacking_points(u) == 5


def test_battalion_stacking_points():
    """Battalion = 1 SP (rules_tables.json 9.4)."""
    u = Unit(
        id="bat", name="Battalion",
        nationality=Nationality.BRITISH, side=Side.COMMONWEALTH,
        type=UnitType.INFANTRY, size=UnitSize.BATTALION,
    )
    assert HexMap.unit_stacking_points(u) == 1


def test_truck_stacking_points():
    """Truck Convoy = 0 SP, never exerts ZOC (rule 10.11)."""
    u = Unit(
        id="trk", name="Truck",
        nationality=Nationality.BRITISH, side=Side.COMMONWEALTH,
        type=UnitType.TRUCK, size=UnitSize.REGIMENT,
    )
    assert HexMap.unit_stacking_points(u) == 0


# ── 10.11/10.21 ZOC parametrized tests ───────────────────────────────────────

_ZOC_CASES = load_fixture("zoc_10_11_10_21")


@pytest.mark.parametrize(
    "case", _ZOC_CASES,
    ids=[case_id(c) for c in _ZOC_CASES],
)
def test_zoc_projection_and_extension(case):
    """
    For each fixture case verify:
    (a) projects_zoc — does the unit/hex meet the rule 10.11 ZOC eligibility?
    (b) zoc_extends_through_hexside — is the crossing hexside a ZOC blocker?

    For 10.21c (entry-prohibition) cases the hexside is "None" but the expected
    extension is False due to target hex impassability; those are covered in the
    separate integration test test_zoc_10_21c_salt_marsh.
    """
    inp = case["inputs"]
    exp = case["expected"]

    unit_type = _FIXTURE_UNIT_TYPE.get(inp["unit_type"], UnitType.INFANTRY)
    unit_size = _FIXTURE_UNIT_SIZE.get(inp["unit_size"], UnitSize.BATTALION)
    cohesion  = inp["unit_cohesion"]
    hex_total = inp["hex_total_sp"]
    crossing  = _FIXTURE_HEXSIDE.get(inp["crossing_hexside"], HexsideFeature.NONE)

    u = Unit(
        id="test-zoc", name="ZOC test",
        nationality=Nationality.BRITISH, side=Side.COMMONWEALTH,
        type=unit_type, size=unit_size, motorized=True,
        cohesion=cohesion, hex_id=_FROM,
    )

    sp = HexMap.unit_stacking_points(u)

    # Rule 10.11 eligibility:
    is_never_type       = u.type in _ZOC_NEVER_TYPES
    cohesion_suppress   = cohesion <= -26
    projects_zoc_calc   = (
        not is_never_type
        and not cohesion_suppress
        and (sp > 1 or hex_total > 1)
    )

    assert projects_zoc_calc == exp["projects_zoc"], (
        f"projects_zoc: got {projects_zoc_calc} "
        f"(type={inp['unit_type']}, size={inp['unit_size']}, sp={sp}, "
        f"hex_total_sp={hex_total}, cohesion={cohesion}), "
        f"expected {exp['projects_zoc']}"
    )

    # Rule 10.21 hexside blocking check (only meaningful when a hexside is specified)
    if crossing != HexsideFeature.NONE and exp["projects_zoc"]:
        blocked       = crossing in _ZOC_BLOCKED_HEXSIDES
        should_extend = exp["zoc_extends_through_hexside"]
        assert (not blocked) == should_extend, (
            f"zoc_extends_through_hexside: hexside={inp['crossing_hexside']!r} "
            f"blocked={blocked}, expected extends={should_extend}"
        )


# ── 10.21c integration: ZOC blocked by entry prohibition ─────────────────────

def test_zoc_10_21c_salt_marsh(tec):
    """
    Tank division at A0101 cannot project ZOC into Salt Marsh A0102 (no track/road).

    Rule 10.21c: ZOC does not extend into a hex that the projecting unit could
    not enter from its present location.  The rulebook's own example is a tank
    battalion and a Salt Marsh.
    """
    from_hex = Hex.from_id(_FROM)
    from_hex.terrain = Terrain.DESERT

    to_hex = Hex.from_id(_TO)
    to_hex.terrain = Terrain.SALT_MARSH  # motorized prohibited without track

    hmap = HexMap({_FROM: from_hex, _TO: to_hex}, tec)

    tank_div = Unit(
        id="tank-div", name="Tank Division",
        nationality=Nationality.BRITISH, side=Side.COMMONWEALTH,
        type=UnitType.ARMOR, size=UnitSize.DIVISION, motorized=True,
        hex_id=_FROM,
    )
    zoc = hmap.zoc_hexes(Side.COMMONWEALTH, [tank_div])
    assert _TO not in zoc, (
        "Tank division must NOT project ZOC into Salt Marsh without track/road "
        "(rule 10.21c)"
    )
