"""
tests/test_supply.py — engine supply rule verification.

Fixtures generated by the oracle agent from cna_rules.txt only (never src/).
Rules covered:
  49.3  Fuel evaporation (all rates, rounding, date boundaries, hot weather)
  52.6  Italian pasta rule (restriction flag, forced disorganization, recovery)
  28.15 Prisoner stores cost (floor division, per-opstage frequency, clamping)
  32.16 Supply-line check (range, ZOC, impassable, dummy/enemy dump)

Design: fixture cases are the oracle; any disagreement requires a PDF audit.
"""
from __future__ import annotations

import json
from datetime import date
from pathlib import Path

import pytest

from conftest import load_fixture, case_id
from src.engine.supply import (
    apply_fuel_evaporation,
    apply_pasta_rule,
    apply_prisoner_stores_cost,
    is_in_supply,
)
from src.models.game_state import GameState
from src.models.hex import Hex, HexsideFeature, Terrain
from src.models.supply import SupplyDump
from src.models.unit import (
    Nationality, Side, Unit, UnitSize, UnitStatus, UnitType,
)


# ── Minimal construction helpers ─────────────────────────────────────────────

def make_gs(turn=1, opstage=1, current_date=None):
    return GameState(
        scenario="test", turn=turn, opstage=opstage,
        current_date=current_date,
    )


def make_unit(
    *,
    nationality=Nationality.BRITISH,
    side=Side.COMMONWEALTH,
    unit_type=UnitType.INFANTRY,
    size=UnitSize.BATTALION,
    motorized=True,
    cpa=0,
    cohesion=0,
    status=UnitStatus.ACTIVE,
    pasta_rule=False,
    pasta_restricted=False,
    hex_id=None,
):
    u = Unit(
        id="test-unit",
        name="Test Unit",
        nationality=nationality,
        side=side,
        type=unit_type,
        size=size,
        motorized=motorized,
        cpa=cpa,
        cohesion=cohesion,
        status=status,
        pasta_rule=pasta_rule,
        pasta_restricted=pasta_restricted,
        hex_id=hex_id,
    )
    return u


def make_dump(*, hex_id, side="commonwealth",
              fuel=0.0, stores=0.0,
              is_dummy=False, is_unlimited=False):
    return SupplyDump(
        id="test-dump",
        hex_id=hex_id,
        side=side,
        fuel=fuel,
        stores=stores,
        is_dummy=is_dummy,
        is_unlimited=is_unlimited,
    )


# ── Rule 49.3: fuel evaporation ───────────────────────────────────────────────

_FUEL_CASES = load_fixture("fuel_evaporation_49_3")


@pytest.mark.parametrize("case", _FUEL_CASES, ids=[case_id(c) for c in _FUEL_CASES])
def test_fuel_evaporation(case):
    inp = case["inputs"]
    exp = case["expected"]

    # SupplyDump has no in_convoy_at_sea flag yet — skip until implemented
    if inp.get("in_convoy_at_sea"):
        pytest.skip("in_convoy_at_sea flag not implemented on SupplyDump")

    dump_side    = inp["dump_side"]
    fuel_before  = inp["fuel_before"]
    current_date = date.fromisoformat(inp["current_date"])
    hot_weather  = inp.get("hot_weather", False)

    dump = SupplyDump(id="d1", hex_id="A0101", side=dump_side, fuel=fuel_before)
    gs = make_gs(current_date=current_date)
    gs.supply_dumps["d1"] = dump

    events = apply_fuel_evaporation(gs, hot_weather=hot_weather)

    assert dump.fuel == pytest.approx(exp["fuel_after"]), (
        f"fuel_after: got {dump.fuel}, expected {exp['fuel_after']}"
    )
    expected_lost = exp["lost"]
    if expected_lost > 0:
        assert len(events) == 1
        assert events[0].data["lost"] == pytest.approx(expected_lost)
    else:
        assert len(events) == 0


# ── Rule 52.6: Italian pasta rule ─────────────────────────────────────────────

_PASTA_CASES = load_fixture("pasta_rule_52_6")

_STATUS_MAP = {s.value: s for s in UnitStatus}


@pytest.mark.parametrize("case", _PASTA_CASES, ids=[case_id(c) for c in _PASTA_CASES])
def test_pasta_rule(case):
    inp = case["inputs"]
    exp = case["expected"]

    unit = make_unit(
        nationality=Nationality.ITALIAN,
        side=Side.AXIS,
        cohesion=inp["cohesion"],
        status=_STATUS_MAP[inp["status_before"]],
        pasta_rule=inp["pasta_rule"],
        pasta_restricted=inp["pasta_restricted_before"],
    )
    gs = make_gs()

    event = apply_pasta_rule(
        unit,
        received_pasta_point=inp["received_pasta_point"],
        game_state=gs,
    )

    assert unit.pasta_restricted == exp["pasta_restricted_after"], (
        f"pasta_restricted_after: got {unit.pasta_restricted}"
    )
    assert unit.status.value == exp["status_after"], (
        f"status_after: got {unit.status.value!r}, expected {exp['status_after']!r}"
    )
    assert (event is not None) == exp["event_emitted"], (
        f"event_emitted: got {event is not None}"
    )
    if exp.get("event_type") is not None and event is not None:
        assert event.type == exp["event_type"]
    if exp.get("forced_disorganized") is not None and event is not None:
        assert event.data.get("forced_disorganized") == exp["forced_disorganized"]


# ── Rule 28.15: prisoner stores cost ─────────────────────────────────────────

_PRISONER_CASES = load_fixture("prisoner_stores_28_15")

_PRIS_HEX  = "A0101"
_DUMP_HEX  = "A0102"  # adjacent — nearest dump


@pytest.mark.parametrize("case", _PRISONER_CASES, ids=[case_id(c) for c in _PRISONER_CASES])
def test_prisoner_stores(case):
    inp = case["inputs"]
    exp = case["expected"]

    stores_avail    = inp["stores_available"]
    opstages_count  = inp.get("opstages_this_game_turn", 1)

    dump = make_dump(hex_id=_DUMP_HEX, side="commonwealth", stores=stores_avail)
    gs = make_gs()
    gs.supply_dumps["test-dump"] = dump

    total_owed = 0.0
    for _ in range(opstages_count):
        events = apply_prisoner_stores_cost(
            {_PRIS_HEX: inp["prisoner_points"]}, gs
        )
        for ev in events:
            total_owed += ev.data.get("stores_owed", 0.0)

    # stores_consumed in fixture = amount owed per rule (not clamped to available)
    assert total_owed == pytest.approx(exp["stores_consumed"]), (
        f"stores_consumed (owed): got {total_owed}, expected {exp['stores_consumed']}"
    )
    # stores_after = what remains in the dump after drawing (clamped at 0)
    assert dump.stores == pytest.approx(exp["stores_after"]), (
        f"stores_after: got {dump.stores}, expected {exp['stores_after']}"
    )


# ── Rule 32.16: supply-line check (concrete scenario tests) ───────────────────

_TEC_PATH = Path(__file__).parent.parent / "data" / "extracted" / "rules_tables.json"


def _make_hmap(hexes: dict):
    from src.engine.hex_map import HexMap
    with _TEC_PATH.open() as f:
        rules = json.load(f)
    tec = rules.get("terrain_effects_chart", rules)
    return HexMap(hexes, tec)


def _dhex(hex_id: str, *, feature_dir=None, feature=HexsideFeature.NONE) -> Hex:
    """Desert hex, optionally with one hexside feature."""
    h = Hex.from_id(hex_id)
    h.terrain = Terrain.DESERT
    if feature_dir:
        h.hexsides[feature_dir] = feature
    return h


def _supply_gs(unit, dump, current_date=None):
    gs = make_gs(current_date=current_date or date(1941, 6, 15))
    gs.units[unit.id] = unit
    gs.supply_dumps[dump.id] = dump
    return gs


def test_in_supply_adjacent_dump():
    """Unit adjacent to friendly dump; cost=1 ≤ max_range=10 (CPA=20) → in supply."""
    unit = make_unit(cpa=20, hex_id="A0101")
    dump = make_dump(hex_id="A0102", side="commonwealth")
    hexes = {"A0101": _dhex("A0101"), "A0102": _dhex("A0102")}
    gs = _supply_gs(unit, dump)
    hmap = _make_hmap(hexes)
    assert is_in_supply(unit, gs, hmap) is True


def test_in_supply_same_hex_as_dump():
    """Unit co-located with dump; cost=0 ≤ max_range=10 (CPA=20) → in supply."""
    unit = make_unit(cpa=20, hex_id="A0115")
    dump = make_dump(hex_id="A0115", side="commonwealth")
    hexes = {"A0115": _dhex("A0115")}
    gs = _supply_gs(unit, dump)
    hmap = _make_hmap(hexes)
    assert is_in_supply(unit, gs, hmap) is True


def test_out_of_supply_cpa_zero():
    """CPA=0 → max_range=0; engine returns False immediately (rule 32.16)."""
    unit = make_unit(cpa=0, hex_id="A0115")
    dump = make_dump(hex_id="A0115", side="commonwealth")
    hexes = {"A0115": _dhex("A0115")}
    gs = _supply_gs(unit, dump)
    hmap = _make_hmap(hexes)
    assert is_in_supply(unit, gs, hmap) is False


def test_out_of_supply_dummy_dump():
    """Friendly dump flagged as dummy → no supply (rule 32.16 / 32.18)."""
    unit = make_unit(cpa=20, hex_id="A0101")
    dump = make_dump(hex_id="A0102", side="commonwealth", is_dummy=True)
    hexes = {"A0101": _dhex("A0101"), "A0102": _dhex("A0102")}
    gs = _supply_gs(unit, dump)
    hmap = _make_hmap(hexes)
    assert is_in_supply(unit, gs, hmap) is False


def test_out_of_supply_enemy_dump():
    """Dump belongs to enemy → CW unit cannot draw supply (rule 32.16)."""
    unit = make_unit(cpa=20, hex_id="A0101")  # Commonwealth
    dump = make_dump(hex_id="A0102", side="axis")  # Axis dump
    hexes = {"A0101": _dhex("A0101"), "A0102": _dhex("A0102")}
    gs = _supply_gs(unit, dump)
    hmap = _make_hmap(hexes)
    assert is_in_supply(unit, gs, hmap) is False


def test_supply_at_max_range_boundary():
    """CPA=4: max_range=2; dump 2 desert hexes away; cost=2 == max_range → in supply."""
    # A0101 → A0102 → A0103 = 2 hops, each costing 1 CP = path cost 2
    unit = make_unit(cpa=4, hex_id="A0101")
    dump = make_dump(hex_id="A0103", side="commonwealth")
    hexes = {
        "A0101": _dhex("A0101"),
        "A0102": _dhex("A0102"),
        "A0103": _dhex("A0103"),
    }
    gs = _supply_gs(unit, dump)
    hmap = _make_hmap(hexes)
    assert is_in_supply(unit, gs, hmap) is True


def test_out_of_supply_exceeds_range():
    """CPA=4: max_range=2; dump 3 desert hexes away; cost=3 > max_range → out of supply."""
    unit = make_unit(cpa=4, hex_id="A0101")
    dump = make_dump(hex_id="A0104", side="commonwealth")
    hexes = {
        "A0101": _dhex("A0101"),
        "A0102": _dhex("A0102"),
        "A0103": _dhex("A0103"),
        "A0104": _dhex("A0104"),
    }
    gs = _supply_gs(unit, dump)
    hmap = _make_hmap(hexes)
    assert is_in_supply(unit, gs, hmap) is False
